spring:
    application:
        name: starship-manager

    profiles:
        active: tst

    datasource:
        url: jdbc:h2:mem:starships
        username: root
        password: 1234
        driverClassName: org.h2.Driver

sm:
    jwt:
        expiration: ${JWT_EXPIRATION}
        issuer: ${JWT_ISSUER}
        secret: ${JWT_SECRET}
