spring:
    application:
        name: starship-manager

    profiles:
        active: pro

sm:
    jwt:
        expiration: ${JWT_EXPIRATION}
        issuer: ${JWT_ISSUER}
        secret: ${JWT_SECRET}

    cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS}
        allowed-methods: ${CORS_ALLOWED_METHODS}
        allowed-headers: ${CORS_ALLOWED_HEADERS}
