CREATE TABLE public.starships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)     NOT NULL,
    length     DOUBLE PRECISION NOT NULL,
    beam       DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP        NOT NULL,
    updated_at TIMESTAMP        NOT NULL,
    CONSTRAINT pk_starships PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE public.starships
    ADD CONSTRAINT uc_starships_name UNIQUE (name);

ALTER TABLE public.users
    ADD CONSTRAINT uc_users_username UNIQUE (username);